tunga-io/tunga-web

src/app.js, src/components/DeveloperProfile.jsx, src/css/style.less, src/index.ejs
```
[ ] Bugfix
[x ] Feature
```
#194 
Display of developers profile
```
[ ] Yes
[x ] No
```
=> Developer profiles

src/routes/CodeOfConduct.jsx
I was suggesting that the statement be changed to make a correct grammer statement. Please if you find it fitting make the change. Thank you
=> Grammer change

src/components/projects/Docs.jsx, src/scss/tunga.scss
```
[ ] Bugfix
[x ] Feature
```
Issue Number(s):#343
```
[ ] Yes
[ ] No
```
=>  issue: #343 Create_Documentation_component.

src/components/projects/Plan.jsx, src/components/projects/ProjectManagement.jsx, src/components/projects/ProjectPlanningForm.jsx, src/components/utils/auth.js, src/scss/tunga.scss
Create Planning component for project workflow page
```
[ ] Bugfix
[YES ] Feature
```
Issue Number(s): #345 
```
[ ] Yes
[ ] No
```
=> Create Planning component for project workflow page

src/components/dashboard/projects/OpportunityDetails.jsx
```
[X ] Bugfix
[ ] Feature
```
Opportunities with skillsets that a developer does not exhibit makes the web app to crash
Every developer can apply for an opportunity
```
[ ] Yes
[ ] No
```
=> fix opportuinty

src/components/sidenav/index.jsx, src/latest-landing/home/OurService/ServiceCard/ServiceCard.js, src/latest-landing/home/OurService/ServiceCard/ServiceCard.scss, src/latest-landing/shared/PageScroll/PageScroll.js
- Adds unique urls per section
- Switches between videos and images on hover for service cards
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> New designs

src/latest-landing/home/OurService/OurService.js, src/latest-landing/home/OurService/OurService.scss
Fixes our service carousel 
```
[x] Bugfix
```
=> Fix carousel

src/latest-landing/home/OurService/OurService.js, src/latest-landing/home/OurService/OurService.scss, src/latest-landing/shared/PageScroll/JumpToTop/JumpToTop.scss
Updates jump to top button position
```
[x ] Bugfix
```
=> Jump btn position

.gitignore, src/components/dashboard/projects/SelectDaysModal.jsx, src/components/dashboard/projects/Settings.jsx, src/scss/tunga.scss
```
[x] Feature
```
- Currently, project reports are requested from developers even when they are not relevant.
Issue Number(s): [#439](https://github.com/tunga-io/tunga-web/issues/439)
- Project managers can tweak the recurrence of asking for reports from reporters, they can, for example, ask for progress reports on Tuesdays and Thursdays
```
[x] No
```
=> Add ability for custom reports request

src/actions/utils/api.js, src/components/dashboard/projects/ProgressReport.jsx, src/components/dashboard/projects/ProgressReportForm.jsx, src/components/dashboard/projects/common/SurveyIcon.js, src/scss/tunga.scss
```
[x] Feature
```
- Number scale to rate deliverables in the developer report
- A developer has to fill the `Any other remarks or questions` text field
- Adds `ahead of schedule` as one of the statuses options
- Smiley scale to rate deliverables for the developer
- If the rate of the deliverables is below 4, developer answers: ` What can be done to increase the quality of the deliverables`
- The developer no longer has to fill the `Any other remarks or questions` text field
```
[x] No
```
=> Modify fields for Developer Report

src/actions/utils/api.js, src/components/dashboard/network/UserForm.jsx, src/components/dashboard/settings/Experience.jsx, src/components/dashboard/settings/modals/WorkForm.jsx, src/latest-landing/home/DevProfile/DevProfile.js, src/latest-landing/home/DevProfile/Experience/Experience.js, src/latest-landing/home/DevProfile/Experience/Experience.scss, src/legacy/constants/Api.js
```
[x] Feature
[x] Code style update (formatting, local variables)
[x] Documentation content changes
```
- 
- Admin can select a user from user types when inviting a user
- User can add project and repository links when adding what they have worked on
- Clients/Users can view projects and/or repositories of developers/designers
```
[x] No
```
=> Add portfolio links

src/components/dashboard/settings/modals/WorkForm.jsx, src/components/utils/validation.js
```
[x] Feature
```
- User can add  random text to project and repository link fields
- User can submit project and repository links that are not valid URLs
```
[x ] No
```
=> Add links validation

src/components/dashboard/projects/ProgressReportForm.jsx
```
[x] Bugfix
```
- When a project is on `behind and stuck`, PM/developer can not post to the report to the server
- PM/developer can now successfully post/update a report to the server when the project is` behind and stuck`
```
[x] No
```
=> passing other as stuck reason

src/components/dashboard/settings/modals/WorkForm.jsx, src/components/utils/validation.js
```
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
- User can add random text to repository and project links fields
- The form elements in the `WorkForm` file were being changed from uncontrolled components to controlled components on adding work entry. 
- The user gets a warning on adding text that doesn't match a Url pattern
- I specify default values in the state to prevent change from uncontrolled components to controlled components
```
[x] No
```
=> Add url validation

src/components/dashboard/projects/Survey.jsx
```
[ ] Bugfix
[x] Feature
```
When submitting a client survey, the submit button doesn't change even when the survey has been submitted
After submitting the button changes to "Update rating".
```
[ ] Yes
[x] No
```
=> Client survey submit button state fix

src/reducers/AuthReducers.js
```
[x] Bugfix
[ ] Feature
```
when one inserts wrong credentials it loading and button remains disabled
when wrong credentials are inserted, the user gets error message but the loading state is removed and the button is made active again
```
[ ] Yes
[x] No
```
=> frixed continous loading on failed login

src/components/dashboard/projects/Survey.jsx
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> chaning Ratings to Rating

src/components/dashboard/projects/Team.jsx
```
[ ] Bugfix
[x] Feature
```
Clients should not be able to add team members
Button for add new developers is removed when client has logged in
```
[ ] Yes
[x] No
```
=> Client feature change

src/components/dashboard/projects/Team.jsx
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> Prevent client from adding or removing project managers

readme.md
```
[x] Bugfix
[ ] Feature
```
Readme doesnt have installation instruction of graphicsmagick
Readme has installation instruction of graphicsmagick
```
[ ] Yes
[x] No
```
=> add graphicsmagick installation to readme

src/latest-landing/home/OurService/OurService.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> remove developer on demand service

src/latest-landing/layout/Header/Header.scss
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix background video

src/latest-landing/layout/Header/Header.scss
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> added parent reference to scss rule

src/templates/index.ejs
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> calendly fix

src/templates/index.ejs
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Calendly hotfix

src/latest-landing/home/News/Publications/PublicationDownload/PublicationDownload.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> change handle submit to es7

src/actions/ProjectActions.js
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> hot fix for not showing archived projects

src/actions/ProjectActions.js
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
=> Projects bug fix

src/components/core/Upload.jsx
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fixed windows problem on file uploads

package-lock.json, package.json, src/actions/ProfileActions.js, src/components/core/CountrySelector.jsx, src/components/core/CustomInputGroup.jsx, src/components/dashboard/settings/Profile.jsx, src/components/dashboard/settings/modals/EducationForm.jsx, src/components/dashboard/settings/modals/WorkForm.jsx
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> Form error validation

src/components/dashboard/projects/OpportunityManagement.jsx, src/components/dashboard/projects/Settings.jsx, src/scss/tunga.scss
```
[ ] Bugfix
[x] Feature
```
Cant edit opportunity details
able to edit title and description of the opportunity
```
[ ] Yes
[x] No
```
=> update title of opportunity fix
